import Foundation
import SwiftData

/// A single money movement. `isExpense == true` means money out, false means income.
/// Amounts are stored as **integer cents** (see `Money`) to avoid float drift.
@Model
final class Transaction {
    var id: UUID
    /// Positive magnitude in cents; direction comes from `isExpense`.
    var amountCents: Int
    var isExpense: Bool
    var note: String
    var date: Date
    /// Optional so a transaction survives its category being deleted.
    var category: Category?

    /// Raw value of `PaymentMethod`. Defaults to "cash".
    var paymentMethodRaw: String = PaymentMethod.cash.rawValue

    /// True once matched to a statement line during reconciliation.
    var isReconciled: Bool = false

    /// True if auto-created from an imported statement (vs hand-keyed).
    var createdFromStatement: Bool = false

    /// The `CreditCardAccount.id` this transaction is attached to (nil = none/cash).
    var cardID: UUID? = nil

    /// True if this row was generated by a recurring rule (shows a ↻ badge).
    var isRecurring: Bool = false

    /// The `RecurringRule.id` that generated this row (nil if hand-keyed or
    /// `isRecurring` is false). Used to dedupe materialization by rule identity
    /// rather than guessing from amount+note, which falsely collides when two
    /// rules share an amount/note, or misses a match after the rule is edited.
    var ruleID: UUID? = nil

    /// Last local modification time, used for last-write-wins sync with the backend.
    var updatedAt: Date = Date.now

    init(
        id: UUID = UUID(),
        amountCents: Int,
        isExpense: Bool = true,
        note: String = "",
        date: Date = .now,
        category: Category? = nil,
        paymentMethod: PaymentMethod = .cash,
        isReconciled: Bool = false,
        createdFromStatement: Bool = false,
        cardID: UUID? = nil,
        isRecurring: Bool = false,
        ruleID: UUID? = nil
    ) {
        self.id = id
        self.amountCents = abs(amountCents)
        self.isExpense = isExpense
        self.note = note
        self.date = date
        self.category = category
        self.paymentMethodRaw = paymentMethod.rawValue
        self.isReconciled = isReconciled
        self.createdFromStatement = createdFromStatement
        self.cardID = cardID
        self.isRecurring = isRecurring
        self.ruleID = ruleID
    }

    /// Convenience accessor bridging the raw string to the enum.
    var paymentMethod: PaymentMethod {
        get { PaymentMethod(rawValue: paymentMethodRaw) ?? .cash }
        set { paymentMethodRaw = newValue.rawValue }
    }

    /// Signed cents: negative for expenses, positive for income.
    var signedCents: Int { isExpense ? -amountCents : amountCents }
}
